export const ACTION_TYPES = {
    FETCH_START: "FETCH_START",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR",
    SET_FIELD: "SET_FIELD",
    SAVE_START: "SAVE_START",
    SAVE_SUCCESS: "SAVE_SUCCESS",
};
