export const DELETE_BARANGAY_ACTION_TYPES = {
    DELETE_DIALOG_OPEN: "DELETE_DIALOG_OPEN",
    DELETE_DIALOG_CLOSE: "DELETE_DIALOG_CLOSE",
    DELETE_START: "DELETE_START",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    CLEAR_ALERT: "CLEAR_ALERT",
    DATA_TO_DELETE: "DATA_TO_DELETE",
};
