export const EDIT_BARANGAY_ACTION_TYPES = {
    SET_FIELD: "SET_FIELD",
    EDIT_DIALOG_OPEN: "EDIT_DIALOG_OPEN",
    EDIT_DIALOG_CLOSE: "EDIT_DIALOG_CLOSE",
    LOAD_DATA_TO_EDIT: "LOAD_DATA_TO_EDIT",
    SAVE_START: "SAVE_START",
    SAVE_SUCCESS: "SAVE_SUCCESS",
    SAVE_ERROR: "SAVE_ERROR",
    CLEAR_ALERT: "CLEAR_ALERT",
};
